### ISSUE TITLE
Purchased books may not contain parseable metadata

### ISSUE THREAD

**Issue by Styphax** [marcus-crane/october#47]
Hi Marcus,

I ran into the following error when trying to sync my highlights from a Kobo Clara HD for the first time:

_There was a problem sending your highlights: parsing time "" as "2006-01-02T15:04:05.000": cannot parse "" as "2006"_
[2022-05-10.log]

Log is attached: (https://github.com/marcus-crane/october/files/8660567/2022-05-10.log)

Any idea as to what might be the problem?

Many thanks,
Kilian

**Comment by marcus-crane** [comment]
Sure, the problem is that October wasn't able to find a timestamp for that bookmark as it says on the tin 😅 

I didn't know that was possible so I'll have to add something to handle that case.

Out of interest, is this book purchased or sideloaded? I assume purchased because there are some keys in there like `"IsPurchaseable":true`

I haven't explicitly tested October with purchased books (the official Readwise extension supports them) so they may have some field present and others missing which October chokes on.

**Comment by Styphax** [comment]
Indeed, this book was purchased. Might try temporarily removing it from the device then.

Thank you for clarifying!

**Comment by marcus-crane** [comment]
Hi @Styphax,

Sorry for the delay in addressing this. I had a look at the metadata for purchased books and my assumption here was entirely wrong.

Instead, it's possible to have bookmarks without a creation date (I'm not sure how just yet) so I've released `v1.1.1` which handles these edge cases and should resolve your issue.

Feel free to reopen this issue if you have further issues or file a new one.

Thanks!
