### ISSUE TITLE
Kobo Desktop 

### ISSUE THREAD

**Issue by kahyalar** [marcus-crane/october#59]
Hello, 

Tool looks promising but I was wondering, is there any support on Kobo's Desktop Reader app for Mac?

Looking forward!

**Comment by marcus-crane** [comment]
Ah interesting, October doesn't have any support for the Desktop Reader app (as I don't use it myself) but I can have a look at how complex it would be to support.

I didn't realise you can actually read eBooks within it which is interesting, although I imagine they're only store bought books.

Do you know how highlight syncing works like if you make highlights with the Desktop Reader, do they sync back to your eReader and vice versa?

**Comment by marcus-crane** [comment]
I'm actually quite surprised but Kobo Desktop works out of the box with no changes required to October because it uses the exact same database layout at the Kobo itself.

<img width="1361" alt="CleanShot 2022-06-27 at 22 55 04@2x" src="https://user-images.githubusercontent.com/14816406/175925913-93d2776c-dbf6-416d-a5ca-0c0c3e132c5a.png">

You just need to copy `~/Library/Application Support/Kobo/Kobo Desktop Edition/Kobo.sqlite` somewhere that October can see (ie; your desktop) and then load it in using the "Load in a local Kobo database (advanced)" button

`cp ~/Library/Application\ Support/Kobo/Kobo\ Desktop\ Edition/Kobo.sqlite ~/Desktop` should do the trick

Now there are a couple of caveats however.

I only have a couple of Kobo store books and I wasn't able to get highlights to sync between the copy I had on my eReader and the desktop app.

Syncing the desktop app database successfully merged those highlights alongside the highlights I had already synced with my eReader but you could end up doing double highlights and that if you highlight the same passage twice between the two. If you just use the desktop app then that isn't a problem.

I haven't tested out syncing with the mobile app yet either so I'm not sure how that'll behave.

The other thing is that October may appear to take ages to sync if you have a few books in Readwise, despite it only uploading a handful of highlights.

That's because it'll be looking for cover images so I really need to do a patch that tells it not to look for covers if you load a local database.

On a side note, the desktop app would crash whenever I add annotations but they still get saved. It's just annoying though.

**Comment by kahyalar** [comment]
Hey, it worked flawlessly. I wasn't expecting it to that smooth as you said 😃 

Thanks a lot for responding this fast! 

Best,
F

**Comment by marcus-crane** [comment]
No problem! I need to get back to the rewrite so seeing interest in the program is a good motivator 🙂
