### ISSUE TITLE
Question: Possible to execute on ereader device

### ISSUE THREAD

**Issue by globalhuman** [marcus-crane/october#74]
Hi, 

It seems that there are many devices which are wifi enabled. Would it be possible to sync notes directly to Readwise from the device rather than having to use a USB to extract the highlights and database files? 

I currently use a tool called [kobli](https://kobli.me/) which accomplishes a very similar feat, but instead of syncing to Readwise it syncs to it's own cloud area. 

I would hope that it might be possible to draw upon that technology and adapt October to be used on device to improve the workflow and "liveness" of the information rather than requiring a manual step.

**Comment by marcus-crane** [comment]
Hey there,

Thanks for mentioning Koblime. I hadn't heard of it before so it seems neat although a bit unfortunately that it's closed source.

While I have considered it before, I don't think I would necessarily expand into trying to do anything wireless just because of the complexity involved in modifying the official firmware and all that.

You'd probably still want something to do all of the logic of bundling highlights which would probably be well out of my skill set to hack into the Kobo's firmware itself so then you'd probably end up having October receive data wireless at which point you might as well just plug in via USB since it's much faster.

I'm also looking at treating the Kobo as a USB by storing sync state on the device which would probably be a pain to deal with wireless since you have to handle all the probable error cases that are less likely with a cable connection.

Lastly, I personally only export my highlights like once every one or two weeks so I can't say I'd get any benefit out of it myself.

As an alternative, and probably a better place to look for higher levels of modification, KOReader is an alternative Kobo firmware that has Readwise support so you should be able to wirelessly sync using it: https://github.com/koreader/koreader/wiki/Highlight-export

I haven't tried it personally though so I'm not sure how it's implemented or how well it works
