### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Bwauman** [marcus-crane/october#84]
I have an issue with...

---

Even when I use october to sync highlights from my kobo (libra2 - device option ) or the option to select the sqlite-database, I got the message: 'There was a problem sending your highlights: received a non-200 status code from Readwise: code 400.'

I validated the readwise-token. Was ok. Viewed the logs:

{"level":"info","msg":"Logger should be initialised now","time":"2023-05-11T17:03:50+02:00"}
{"level":"info","msg":"Backend is about to start up","time":"2023-05-11T17:03:50+02:00"}
{"kobos_found":1,"level":"info","msg":"Detected one or more Kobos","time":"2023-05-11T17:03:50+02:00"}
{"device_id":"00000000-0000-0000-0000-000000000388","level":"info","msg":"Found an attached device","time":"2023-05-11T17:03:50+02:00"}
{"kobos_found":1,"level":"info","msg":"Detected one or more Kobos","time":"2023-05-11T17:03:50+02:00"}
{"device_id":"00000000-0000-0000-0000-000000000388","level":"info","msg":"Found an attached device","time":"2023-05-11T17:03:50+02:00"}
{"batch_count":1,"highlight_count":0,"level":"info","msg":"Successfully parsed highlights","time":"2023-05-11T17:03:57+02:00"}
{"level":"error","msg":"Received a non-200 response from Readwise","response":"{\"non_field_errors\":[\"No data provided\"]}","status_code":400,"time":"2023-05-11T17:03:57+02:00"}
{"batch_count":1,"highlight_count":0,"level":"info","msg":"Successfully parsed highlights","time":"2023-05-11T17:07:10+02:00"}
{"level":"error","msg":"Received a non-200 response from Readwise","response":"{\"non_field_errors\":[\"No data provided\"]}","status_code":400,"time":"2023-05-11T17:07:12+02:00"}
{"level":"info","msg":"Successfully validated token against the Readwise API","time":"2023-05-11T17:11:05+02:00"}

Can't figure out what is going wrong. Do you? And what can I do about it?

<details><summary>System Details</summary><ul><li>Version: v1.3.2</li><li>Platform: darwin</li><li>Architecture: arm64</li>
</details>

**Comment by marcus-crane** [comment]
Hi @Bwauman,

As far the content on your device, are you using store-purchased books only or are you mainly sideloading content? Purchased titles aren't sent through to Readwise in the latest release (from a little while ago now) but it seems to be a pretty popular use case so October should really handle it better (ie; try to detect store purchased books and notify the user of their options)

Thanks

**Comment by Bwauman** [comment]
Hello Marcus,

Thanks for the answer!
Yes I have mainly purchased books on my KOBO device.
Is that the reason? Do you have the intention to solve (in the mining that they will included in the near future) that problem?

Kind regards,
Bart Wauman


On 27 May 2023, at 06:55, Marcus Crane ***@***.***> wrote:



Hi,

<https://github.com/Bwauman>
Bwauman - Overview<https://github.com/Bwauman>
protection.outlook.com<https://github.com/Bwauman>
[61352724.png]<https://github.com/Bwauman>


As far the content on your device, are you using store-purchased books only or are you mainly sideloading content? Purchased titles aren't sent through to Readwise in the latest release (from a little while ago now) but it seems to be a pretty popular use case so October should really handle it better (ie; try to detect store purchased books and notify the user of their options)

Thanks

**Comment by marcus-crane** [comment]
Hey @Bwauman,

The latest version of October only sync highlights from sideloaded books which was what October was intended for.

While it did sync store purchased books, it was never something that has been intentional and mainly worked accidentally.

I had disabled it as there is an official Readwise integration but as some users have mentioned, it doesn't always work for them.

As for why it was disabled, there are a handful of users who have both sideloaded books and the official Readwise integration so they end up with duplicate highlights.

What really should happen here is that October notifies the user if it sees store brought books and asks you if you want to sync those as well, in order to avoid duplicate syncing.

In the meantime, you can download the last version that supports store purchased books from here:

https://github.com/marcus-crane/october/releases/tag/v1.3.1

You won't be missing out on any features and I'll notify you once a new version is out that syncs store books again.

Kind Regards

**Comment by marcus-crane** [comment]
Hey @Bwauman,

Hey @johnnyfleet,

I've just released [v1.4.0](https://github.com/marcus-crane/october/releases/tag/v.1.4.0) which fixes some bugginess with how highlights were being queried in general.

It also adds a toggle in Settings to enable syncing of store purchased books. It's opt-in just to ensure users are aware that it will cause duplication if they are also using the official Readwise Kobo integration but please let me know if this fixes your issue
